import Waves from '../../../components/app/waves.jsx';
import env from '../../../client-envs/current.js';
import { onMount } from 'solid-js';
import Swal from 'sweetalert2';
import request from '../../../helpers/request.js';
import Anchor from '../../../components/app/anchor.jsx';
import InputText from '../../../components/app/input-text.jsx';

async function getEmail() {
  const urlParams = new URLSearchParams(window.location.search);
  const email = urlParams.get('email');
  if (email === null || email === undefined) {
    await Swal.fire({
      title: 'Oops',
      text: `Something unexpected happened. Please request support directly at ${env.SUPPORT_EMAIL}`,
      confirmButtonText: 'OK',
    });
  }
  return email;
}

async function confirmEmail(email) {
  Swal.fire({ title: 'Please wait ...' });
  const responseJson = await request('POST', '/confirm-email', { email }, null);
  if (responseJson.error) {
    await Swal.fire({
      title: 'Oops',
      text: responseJson?.error?.message,
      confirmButtonText: 'OK',
    });
  } else {
    await Swal.fire({
      title: 'Success',
      text: 'Your email has been confirmed!',
      confirmButtonText: 'OK',
    });
    window.location.href = '/app/signin';
  }
}

function EmailConfirmation() {
  onMount(async () => {
    const email = await getEmail();
    await confirmEmail(email);
  });
  return (
    <div
      class="grid grid-cols-1 md:grid-cols-10 md:text-lg text-center"
      style={{ 'font-family': 'Poppins, sans-serif' }}
    >
      <div class="col-start-1 col-span-1 md:col-start-1 md:col-span-full text-3xl md:text-5xl">
        <h1 class="font-[Wizzta] p-8 text-purple-600">TalentSourcery</h1>
      </div>
      <div class="col-start-1 col-span-1 md:col-start-3 md:col-span-6 flex flex-row p-4 bg-white border-2 border-purple-500 rounded-2xl">
        <div class="grid grid-cols-2">
          <div class="col-start-1 col-span-2 md:col-span-1 flex flex-col">
            <InputText inputClass="invisible w-[90%] my-0 py-0 text-center"></InputText>
            <Anchor href="/signin" inputClass="mx-auto mt-[10%] mb-[20%]">
              Go to sign in
            </Anchor>
          </div>
          <div class="col-start-2 col-span-1 invisible md:visible mx-auto my-auto">
            <img
              id="sourcerer"
              src="/images/sourcerer.png"
              alt="TalentSourcerer"
              title="TalentSourcerer generated by AI"
              class="w-64 h-64"
            />
          </div>
        </div>
      </div>
      <Waves />
    </div>
  );
}

export default EmailConfirmation;
