import Waves from '../../../components/app/waves.jsx';
import { onMount } from 'solid-js';
import Swal from 'sweetalert2';
import request from '../../../helpers/request.js';
import Anchor from '../../../components/app/anchor.jsx';
import Button from '../../../components/app/button.jsx';
import InputText from '../../../components/app/input-text.jsx';
import InputPassword from '../../../components/app/input-password.jsx';

async function addSubmitListener() {
  const formEl = document.querySelector('#form');
  formEl.addEventListener(
    'submit',
    async (event) => {
      event.preventDefault();
      const formData = new FormData(formEl);
      const userCredentials = {
        email: formData.get('email'),
        password: formData.get('password'),
      };
      const responseJson = await request('POST', '/signin', userCredentials);
      if (responseJson.success === true) {
        localStorage.setItem(
          'talent-sourcery-session-jwt',
          responseJson.data.jwt,
        );
        window.location.href = '/app/dashboard';
      } else if (responseJson?.error) {
        await Swal.fire({
          title: 'Oops',
          text: responseJson?.error?.message,
          confirmButtonText: 'OK',
        });
      }
    },
    false,
  );
}

function SignIn() {
  onMount(async () => {
    await addSubmitListener();
  });
  return (
    <div class="grid grid-cols-1 md:grid-cols-10 md:text-lg text-center">
      <div class="col-start-1 col-span-1 md:col-start-1 md:col-span-full text-3xl md:text-5xl">
        <h1 class="font-[Wizzta] p-8 text-purple-600">TalentSourcery</h1>
      </div>
      <div class="col-start-1 col-span-1 md:col-start-3 md:col-span-6 flex flex-row p-4 bg-white border-2 border-purple-500 rounded-2xl">
        <div class="grid grid-cols-2">
          <div class="col-start-1 col-span-2 md:col-span-1 flex flex-col">
            <form id="form" class="flex flex-col">
              <InputText
                id="email"
                placeholder="Email"
                required
                inputClass="w-[90%] mt-6 mb-2 text-center text-purple-600"
              ></InputText>
              <InputPassword
                id="password"
                placeholder="Password"
                required
                autocomplete
                inputClass="w-[90%] mb-4 text-center text-purple-600"
              ></InputPassword>
              <Button type="submit" id="submit" inputClass="mx-auto mb-2">
                Sign in
              </Button>
            </form>
            <hr class="w-[90%] h-[0.15rem] mx-auto my-6 bg-purple-400 rounded-2xl"></hr>
            <div class="mt-2 mb-6 flex flex-row justify-center">
              <Anchor href="/app/signup" inputClass="my-0 text-sm">
                Sign up
              </Anchor>
              <Anchor
                href="/app/password-recovery"
                inputClass="mx-4 my-0 text-sm"
              >
                Recover my password
              </Anchor>
            </div>
          </div>
          <div class="col-start-2 col-span-1 invisible md:visible mx-auto my-auto">
            <img
              id="sourcerer"
              src="/images/sourcerer.png"
              alt="TalentSourcerer"
              title="TalentSourcerer generated by AI"
              class="w-64 h-64"
            />
          </div>
        </div>
      </div>
      <Waves />
    </div>
  );
}

export default SignIn;
