import Navbar from '../../components/website/navbar.jsx';
import Footer from '../../components/website/footer.jsx';

function PrivacyPolicy() {
  return (
    <div>
      <Navbar />
      <section class="p-6 pb-8 md:p-12">
        <h1 class="text-3xl md:text-5xl p-4 text-center font-bold">
          Privacy policy
        </h1>
        <h1 class="text-xl md:text-3xl text-center p-4 pb-8">
          Effective date: 1 / January / 2023
        </h1>

        <ol class="list-decimal">
          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Introduction
            </h1>
            <p class="text-md md:text-lg">
              Welcome to <b>TalentSourcery</b>!<br />
              As you have just clicked our Privacy Policy (henceforth “
              <b>Policy</b>”), please pause, grab a cup of coffee and carefully
              read the following pages. It will take you approximately 6
              minutes.
              <br />
              TalentSourcery operates{' '}
              <span class="text-purple-500">talentsourcery.io</span> (“
              <b>Service</b>”).
              <br />
              Our <b>Policy</b> governs your visit to{' '}
              <span class="text-purple-500">talentsourcery.io</span>, including
              subdomains such as{' '}
              <span class="text-purple-500">app.talentsourcery.io</span>, and
              explains how we collect, safeguard and disclose information that
              results from your use of our <b>Service</b>.<br />
              We use your data to provide and improve our <b>Service</b>. By
              using our <b>Service</b>, you agree to the collection and use of
              information in accordance with this <b>Policy</b>. Unless
              otherwise defined in this <b>Policy</b>, the terms used in this{' '}
              <b>Policy</b> have the same meanings as in our Terms of Service (“
              <b>Terms</b>”). Our <b>Terms</b> govern all use of our{' '}
              <b>Service</b> and together with this <b>Policy</b> constitutes
              your agreement with us (“<b>Agreement</b>”). You acknowledge that
              you have read and understood the <b>Agreement</b>, and agree to be
              bound by it.
              <br />
              If you do not agree with, or cannot comply with, the{' '}
              <b>Agreement</b>, then you may not use our <b>Service</b>, but
              please let us know by emailing at{' '}
              <span class="text-purple-500">support@talentsourcery.io</span> so
              we can try to find a solution. The <b>Agreement</b> apply to all
              visitors, users and others who wish to access or use our{' '}
              <b>Service</b>.<br />
              Thank you for being responsible.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Definitions
            </h1>
            <p class="text-md md:text-lg">
              <span class="font-bold">SERVICE</span> means the{' '}
              <span class="text-purple-500">talentsourcery.io</span> website,
              and its subdomains, operated by <b>TalentSourcery</b>.<br />
              <span class="font-bold">PERSONAL DATA</span> means data about a
              living individual who can be identified from that data (or from
              any other information either in our possession or likely to come
              into our possession).
              <br />
              <span class="font-bold">USAGE DATA</span> is data collected
              automatically either generated by the use of <b>Service</b> or
              from its infrastructure itself (for example, the duration of a
              page visit).
              <br />
              <span class="font-bold">TALENT DATA</span> is data collected on
              your behalf when using our <b>Service</b> to source talent.
              <br />
              <span class="font-bold">COOKIES</span> are small files stored on
              your device (computer or mobile device).
              <br />
              <span class="font-bold">DATA CONTROLLER</span> means a natural or
              legal person who (either alone or jointly or in common with other
              persons) determines the purposes for which and the manner in which
              any personal data are, or are to be, processed. For the purpose of
              this <b>Policy</b>, we are a <b>Data Controller</b> of your data.
              <br />
              <span class="font-bold">
                DATA PROCESSORS (OR SERVICE PROVIDERS)
              </span>{' '}
              means any natural or legal person who processes the data on behalf
              of the a <b>Data Controller</b>. We may use the services of
              various providers in order to process your data more effectively.
              <br />
              <span class="font-bold">DATA SUBJECT</span> is any living
              individual who is the subject of <b>Personal Data</b>.<br />
              <span class="font-bold">THE USER</span> is the individual using
              our <b>Service</b>. The <b>User</b> corresponds to the{' '}
              <b>Data Subject</b>, who is the subject of <b>Personal Data</b>.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Information collection and use
            </h1>
            <p class="text-md md:text-lg">
              We collect several different types of information for various
              purposes to provide and improve our <b>Service</b> to you.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Types of data collected
            </h1>
            <p class="text-md md:text-lg">
              <span class="font-bold">Personal Data</span>
              <br />
              While using our <b>Service</b>, we may ask you to provide us with
              certain <b>Personal Data</b> that can be used to contact or
              identify you. Personally identifiable information may include, but
              is not limited to:
              <br />
              <br />
              - Email address
              <br />
              - First name and last name
              <br />
              - Address: state, Province, ZIP/Postal code, City
              <br />
              - Cookies and Usage Data
              <br />
              <br />
              We may use your <b>Personal Data</b> to contact you with
              newsletters, marketing or promotional materials and other
              information that may be of interest to you. You may opt out of
              receiving any, or all, of these communications from us by emailing
              at <span class="text-purple-500">support@talentsourcery.io</span>.
              <br />
              <br />
              <span class="font-bold">Usage Data</span>
              <br />
              We may also collect information that your browser sends whenever
              you visit or access our <b>Service</b> by or through a computer or
              mobile device.
              <br />
              This <b>Usage Data</b> may include information such as your
              computer's Internet Protocol address (i.e. IP address), browser
              type, browser version, the pages of our <b>Service</b> that you
              visit, the time and date of your visit, the time spent on those
              pages, unique device identifiers and other diagnostic data.
              <br />
              When you access our <b>Service</b> with a mobile device, this{' '}
              <b>Usage Data</b> may include information such as the type of
              mobile device you use, your mobile device unique ID, the IP
              address of your mobile device, your mobile operating system, the
              type of mobile Internet browser you use, unique device identifiers
              and other diagnostic data.
              <br />
              <br />
              <span class="font-bold">Talent Data</span>
              <br />
              We may collect information from websites such as{' '}
              <a href="https://linkedin.com" class="text-purple-500 underline">
                LinkedIn
              </a>
              ,{' '}
              <a href="https://github.com" class="text-purple-500 underline">
                GitHub
              </a>{' '}
              and others as you use our <b>Service</b>. Note that the{' '}
              <b>Talent Data</b> collected is publicly available on the
              Internet, and we do not collect private information from any
              individuals or entities. If you believe we have collected private
              information, or we realize that we have collected private
              information, we will take steps to delete such information from
              our servers.
              <br />
              The <b>Talent Data</b> collected by our <b>Service</b> is stored
              temporarily in our servers for your use. It is your responsibility
              to use <b>Talent Data</b> in lawful, upstanding and constructive
              ways. <b>TalentSourcery</b> is not liable for any crimes,
              infringements, abuses and similar behavior you may engage in when
              using <b>Talent Data</b> we collected for you.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Use of data
            </h1>
            <p class="text-md md:text-lg">
              <b>TalentSourcery</b> uses the collected data for various
              purposes:
              <br />
              <br />
              (i) To provide and maintain our <b>Service</b>;<br />
              (ii) To notify you about changes to our <b>Service</b>;<br />
              (iii) To allow you to participate in interactive features of our{' '}
              <b>Service</b> when you choose to do so;
              <br />
              (iv) To provide customer support; <br />
              (v) To gather analysis or valuable information so that we can
              improve our <b>Service</b>;<br />
              (vi) To monitor the usage of our <b>Service</b>;<br />
              (vii) To detect, prevent and address technical issues;
              <br />
              (viii) To fulfill any other purpose for which you provide it;
              <br />
              (ix) To carry out our obligations and enforce our rights arising
              from any contracts entered into between you and us, including for
              billing and collection;
              <br />
              (x) To provide you with notices about your account, including
              expiration and renewal notices, email-instructions, etc.;
              <br />
              (xi) To provide you with news, special offers and general
              information about other goods, services and events which we offer
              that are similar to those that you have already purchased or
              enquired about unless you have opted not to receive such
              information;
              <br />
              (xii) In any other way we may describe when you provide the
              information;
              <br />
              (xiii) For any other purpose with your consent.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Retention of data
            </h1>
            <p class="text-md md:text-lg">
              We will retain your <b>Personal Data</b> only for as long as is
              necessary for the purposes set out in this <b>Policy</b>. We will
              retain and use your <b>Personal Data</b> to the extent necessary
              to comply with our legal obligations. For example, if we are
              required to retain your data to comply with applicable laws,
              resolve disputes, and enforce our legal agreements and policies.
              <br />
              We will also retain <b>Usage Data</b> for internal analysis
              purposes. <b>Usage Data</b> is generally retained for a shorter
              period, except when this data is used to strengthen the security
              or to improve the functionality of our <b>Service</b>, or we are
              legally obligated to retain this data for longer time periods.
              <br />
              In addition, we will retain <b>Talent Data</b> for at least one
              month, counting from the date the <b>Talent Data</b> was
              collected, for your use. After the one month period,{' '}
              <b>Talent Data</b> collected by our <b>Service</b> may be deleted
              anytime.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Transfer of data
            </h1>
            <p class="text-md md:text-lg">
              Your information, including <b>Personal Data</b>, may be
              transferred to, and maintained on, computers located outside of
              your state, province, country or other governmental jurisdiction
              where the data protection laws may differ from those of your
              jurisdiction.
              <br />
              If you are located outside the United States, Brazil and the
              Netherlands and choose to provide information to us, please note
              that we transfer the data, including <b>Personal Data</b>, to the
              mentioned countries and process it there.
              <br />
              Your consent to this <b>Policy</b> followed by your submission of
              such information represents your agreement to that transfer.
              <br />
              <b>TalentSourcery</b> will take all the steps reasonably necessary
              to ensure that your data is treated securely and in accordance
              with this <b>Policy</b> and no transfer of your{' '}
              <b>Personal Data</b> will take place on an organization or a
              country unless there are adequate controls in place including the
              security of your data and other personal information.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Disclosure of data
            </h1>
            <p class="text-md md:text-lg">
              We may disclose personal information that we collect, or you
              provide:
              <br />
              <br />
              (i) Disclosure for law enforcement. Under certain circumstances,
              we may be required to disclose your <b>Personal Data</b> if
              required to do so by law or in response to valid requests by
              public authorities.
              <br />
              (ii) Business Transaction. If we or our subsidiaries are involved
              in a merger, acquisition or asset sale, your Personal Data may be
              transferred.
              <br />
              (iii) Other cases. We may also disclose your information with your
              consent in other cases.
              <br />
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Security of data
            </h1>
            <p class="text-md md:text-lg">
              The security of your data is important to us but remember that no
              method of transmission over the Internet or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your <b>Personal Data</b>, we cannot
              guarantee its absolute security.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Your data protection rights under General Data Protection
              Regulation - GDPR
            </h1>
            <p class="text-md md:text-lg">
              If you are a resident of the European Union (EU) and European
              Economic Area (EEA), you have certain data protection rights,
              covered by GDPR.{' '}
              <a
                href="https://eur-lex.europa.eu/eli/reg/2016/679/oj"
                class="text-purple-500 underline"
              >
                See more here
              </a>
              .<br />
              We aim to take reasonable steps to allow you to correct, amend,
              delete, or limit the use of your <b>Personal Data</b>.<br />
              If you wish to be informed what <b>Personal Data</b> we hold about
              you and if you want it to be removed from our systems, please
              email us at{' '}
              <span class="text-purple-500">support@talentsourcery.io</span>.{' '}
              <br />
              You have the following data protection rights:
              <br />
              <br />
              (i) The right to access. You have the right to access your{' '}
              <b>Personal Data</b> stored in our <b>Service</b>;<br />
              (ii) The right to rectify. You have the right to have your
              information rectified if that information is inaccurate or
              incomplete;
              <br />
              (iii) The right to object. You have the right to object to our
              processing of your <b>Personal Data</b>;<br />
              (iv) The right to restrict. You have the right to request that we
              restrict the processing of your <b>Personal Data</b>;<br />
              (v) The right to data portability. You have the right to be
              provided with a copy of your <b>Personal Data</b> in a structured,
              human or machine readable format;
              <br />
              (vi) The right to withdraw consent. You also have the right to
              withdraw your consent at any time where we rely on your consent to
              process your <b>Personal Data</b>;<br />
              (vii) The right to be forgotten. You have the right to fully
              delete your <b>Personal Data</b> stored in our <b>Service</b>,
              including backups.
              <br />
              <br />
              Please note that we may ask you to verify your identity before
              responding to such requests. Also note that we may not be able to
              provide our <b>Service</b> without some necessary data.
              <br />
              You have the right to complain to a data protection authority
              about our collection and use of your <b>Personal Data</b>. For
              more information, please contact your local data protection
              authority in the European Economic Area (EEA).
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Service providers
            </h1>
            <p class="text-md md:text-lg">
              We may employ third party <b>Service Providers</b> to facilitate
              our <b>Service</b>, provide service on our behalf, or assist us
              perform service related activities.
              <br />
              These third parties have access to your <b>Personal Data</b> only
              to perform these tasks on our behalf and are obligated not to
              disclose or use it for any other purpose.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">Analytics</h1>
            <p class="text-md md:text-lg">
              We may use third party <b>Service Providers</b> to monitor and
              analyze the use of our <b>Service</b>.<br />
              <br />
              <b>Google Analytics</b>
              <br />
              Google Analytics is a web analytics service offered by Google that
              tracks and reports website traffic. Google uses the data collected
              to track and monitor the use of our <b>Service</b>. This data is
              shared with other Google services. Google may use the collected
              data to contextualize and personalize the ads of its own
              advertising network.
              <br />
              For more information on the privacy practices of Google, please
              visit the{' '}
              <a
                href="https://policies.google.com/privacy?hl=en"
                class="text-purple-500 underline"
              >
                Google Privacy Terms web page
              </a>
              .<br />
              We also encourage you to review the{' '}
              <a
                href="https://support.google.com/analytics/answer/6004245"
                class="text-purple-500 underline"
              >
                Google's policy for safeguarding your data
              </a>
              .<br />
              <br />
              {/* <b>Mixpanel</b><br/>

            Mixpanel is provided by Mixpanel Inc.<br/>

            You can prevent Mixpanel from using your information for analytics purposes by opting-out. To opt-out of Mixpanel service, <a href="https://mixpanel.com/optout/" class="text-purple-500 underline">please visit this page</a>.<br/>
            
            For more information on what type of information Mixpanel collects, 
            <a href="https://mixpanel.com/terms/" class="text-purple-500 underline">please visit the Terms of Use page of Mixpanel</a>.<br/> */}
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Continuous integration and continuous delivery tools
            </h1>
            <p class="text-md md:text-lg">
              We may use third-party <b>Service Providers</b> to automate the
              development process of our <b>Service</b>.<br />
              <br />
              <b>GitHub</b>
              <br />
              GitHub is provided by GitHub, Inc.
              <br />
              GitHub is a development platform to host and review code, manage
              projects, and build software.
              <br />
              For more information on what data GitHub collects for what purpose
              and how the protection of the data is ensured,{' '}
              <a
                href="https://help.github.com/en/articles/github-privacy-statement"
                class="text-purple-500 underline"
              >
                please visit the GitHub Privacy Policy page
              </a>
              .
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Behavioral remarketing
            </h1>
            <p class="text-md md:text-lg">
              We may use remarketing services to advertise on third party
              websites to you after you visited our <b>Service</b>. We and our
              third party vendors may use cookies to inform, optimize and serve
              ads based on your past visits to our <b>Service</b>.<br />
              <br />
              <b>Google AdWords</b>
              <br />
              Google AdWords remarketing service is provided by Google Inc.
              <br />
              You can opt-out of Google Analytics for display advertising and
              customize the Google display network ads by visiting{' '}
              <a
                href="http://www.google.com/settings/ads"
                class="text-purple-500 underline"
              >
                the Google Ads Settings page
              </a>
              .<br />
              Google also recommends installing the{' '}
              <a
                href="https://tools.google.com/dlpage/gaoptout"
                class="text-purple-500 underline"
              >
                Google Analytics opt-out extension
              </a>{' '}
              for your web browser. Google Analytics opt-out extension provides
              visitors with the ability to prevent their data from being
              collected and used by Google Analytics.
              <br />
              For more information on the privacy practices of Google, please
              visit the
              <a
                href="https://policies.google.com/privacy?hl=en"
                class="text-purple-500 underline"
              >
                Google Privacy Terms web page
              </a>
              .
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">Payments</h1>
            <p class="text-md md:text-lg">
              We may provide paid products or services within our <b>Service</b>
              . In that case, we use third party services for payment
              processing.
              <br />
              We will not store or collect your payment card details. That
              information is provided directly to our third party payment
              processors whose use of your personal information is governed by
              their privacy policies. These payment processors adhere to the
              standards set by PCI-DSS as managed by the PCI Security Standards
              Council, which is a joint effort of brands like Visa, Mastercard,
              American Express and Discover. PCI-DSS requirements help ensure
              the secure handling of payment information.
              <br />
              The payment processors we work with are:
              <br />
              <br />
              <b>Stripe</b>:<br />
              <a
                href="https://stripe.com/us/privacy"
                class="text-purple-500 underline"
              >
                Their Privacy Policy can be viewed here
              </a>
              .
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Links to other sites
            </h1>
            <p class="text-md md:text-lg">
              Our <b>Service</b> may contain links to other sites that are not
              operated by us. If you click a third party link, you will be
              directed to that third party's site. We advise you to review the
              privacy policy of every site you visit.
              <br />
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Children's privacy
            </h1>
            <p class="text-md md:text-lg">
              Our <b>Service</b> is not intended for use by children under the
              age of 18 (“<b>Children</b>”).
              <br />
              We do not knowingly collect personally identifiable information
              from <b>Children</b>. If you become aware that <b>Children</b>{' '}
              have provided us with <b>Personal Data</b>, please contact us. If
              we become aware that we have collected <b>Personal Data</b> from{' '}
              <b>Children</b> without verification of parental consent, we will
              take steps to remove that information from our servers.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Changes to this Policy
            </h1>
            <p class="text-md md:text-lg">
              We may update our <b>Policy</b> from time to time. We will notify
              you of any changes by posting the new <b>Policy</b> on this page.
              <br />
              We will let you know via email or a prominent notice on our{' '}
              <b>Service</b>, prior to the change becoming effective and update
              the “effective date” at the top of this <b>Policy</b>.<br />
              You are advised to review this <b>Policy</b> periodically for any
              changes. Changes to this <b>Policy</b> are effective when they are
              posted on this page.
            </p>
          </li>

          <li class="p-2 pb-4 md:p-8">
            <h1 class="font-bold pb-4 md:pb-8 text-lg md:text-xl">
              Contact us
            </h1>
            <p class="text-md md:text-lg">
              Please send your feedback, comments, requests for technical
              support via:
              <br />
              Email:{' '}
              <span class="text-purple-500">support@talentsourcery.io</span>.
            </p>
          </li>
        </ol>
      </section>
      <Footer />
    </div>
  );
}

export default PrivacyPolicy;
