const {
  VITE_ENVIRONMENT,
  VITE_BACKEND_URL,
  VITE_FRONTEND_URL,
  VITE_SUPPORT_EMAIL,
  VITE_LOCAL_STORAGE_KEY,
} = import.meta.env;

const env = {
  ENVIRONMENT: VITE_ENVIRONMENT,
  BACKEND_URL: VITE_BACKEND_URL,
  FRONTEND_URL: VITE_FRONTEND_URL,
  SUPPORT_EMAIL: VITE_SUPPORT_EMAIL,
  LOCAL_STORAGE_KEY: VITE_LOCAL_STORAGE_KEY,
};

export default env;
